[pytest]
filterwarnings =
    ignore::DeprecationWarning
    ignore:.*declarative_base.*:DeprecationWarning
    ignore:.*class-based `config`.*:DeprecationWarning
    ignore:.*datetime.datetime.utcnow.*:DeprecationWarning
    ignore:.*crypt is deprecated.*:DeprecationWarning
markers =
    asyncio: mark a test as asynchronous